name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
      - name: Build RHGMTool
        run: dotnet publish --configuration Release --self-contained false --runtime win-x86 /p:PublishSingleFile=false --output ./publish/RHGMTool
      - name: Zip output files
        run: Compress-Archive -Path "./publish/RHGMTool" -DestinationPath RH_GM_Tool.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rusty Hearts GM Tool
          path: RH_GM_Tool.zip
